site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Aloitus: index.md
  - Ohjeet opettajalle: ohje_opettaja.md
  - Rahti:
    - Yleiset ohjeet: ohje_yleinen_rahti.md
    - Spring Boot: 
      - Palvelun julkaisu ilman tietokantaa: ohje_spring_rahti_ilman_tietokantaa.md
      - Palvelimen konfigurointi käyttämään ulkoista tietokantapalvelua: ohje_spring_rahti_tietokannan_konfigurointi.md
  - Reseptit:
    - Spring Boot -palvelun julkaiseminen Rahti-ympäristössä: resepti_spring_rahti.md
    - React-sovelluksen julkaisu: ohje_react_rahti.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - toc.follow
    - navigation.top

  favicon: assets/favicon-192x192.png
  logo: assets/haaga-helia.png
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
