site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Yleistä: index.md
  - Ohjeet opettajalle: ohje_opettaja.md
  - Spring Boot-palvelun julkaisu: ohje_spring_rahti.md
  - React-sovelluksen julkaisu: ohje_react_rahti.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - navigation.tabs
    - toc.integrate
    - navigation.top
  favicon: assets/favicon-192x192.png
  logo: assets/haaga-helia.png
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
