site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Aloitus: index.md
  - Ohjeet opettajalle: ohje_opettaja.md
  - Spring Boot-palvelun julkaisu: ohje_spring_rahti.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - navigation.tabs
    - toc.integrate
    - navigation.top
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - admonition
