site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Aloitus: index.md
  - ohje_opettaja.md
  - ohje_opiskelija.md
  - Reseptit:
    - resepti_spring_rahti.md
    - ohje_react_rahti.md
  - Rahti:
    - Yleiset ohjeet: 
      - ohje_rahti_projektin_luonti.md
      - ohje_rahti_komentorivityokalun_asennus.md
      - ohje_rahti_tietokantapalvelun_luominen.md
      - ohje_rahti_https_konfigurointi.md
      - ohje_rahti_julkaisu_yksityisesta_repositoriosta.md
      - ohje_rahti_virheenjaljitys.md 
    - Spring Boot -ohjeet: 
      - ohje_spring_rahti_ilman_tietokantaa.md
      - ohje_spring_rahti_tietokannan_konfigurointi.md
      - ohje_spring_rahti_jkube_plugin.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - toc.follow
    - navigation.top

  favicon: assets/favicon-192x192.png
  logo: assets/haaga-helia.png
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
